title:               Miguel Torres Costa
url:                 https://blog.mptc.uk
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['README.md', 'CLAUDE.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           posts/:title

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Miguel Costa
  url:               https://blog.mptc.uk
  email:             miguelptcosta1995@gmail.com
