# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:title.html
# permalink:           /:year/:month/:day/:title.html
# relative_permalinks: true

# Setup
title:               Miguel Torres Costa
tagline:             'and my ramblings'
description:         'A mathematician of many hobbies'
url:                 http://lanyon.getpoole.com
baseurl:             ''
excerpt_separator: <!--excerpt ends here-->

# About/contact
author:
  name:              Miguel Torres Costa
  url:               migueltorrescosta.github.io
  email:             miguelptcosta1995@gmail.com
  github:            migueltorrescosta
  google+:           
  goodreads:         migueltorrescosta
  linkedin:          miguel-torres-costa
  steam:             WalkinBot
  stackoverflow:     7358944
  reddit:            WalkinBot

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-gist]