title:               Miguel Torres Costa
url:                 https://migueltorrescosta.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           posts/:title

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Miguel Costa
  url:               migueltorrescosta.github.io
  email:             miguelptcosta1995@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist