# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:title.html
# permalink:           /:year/:month/:day/:title.html
# relative_permalinks: true

# Setup
title:               Miguel Torres Costa
description:         'A mathematician of many hobbies'
url:                 https://migueltorrescosta.github.io
baseurl:             ''
excerpt_separator: <!--excerpt ends here-->

# About/contact
author:
  name:              Miguel Torres Costa
  url:               migueltorrescosta.github.io
  email:             miguelptcosta1995@gmail.com
  github:            migueltorrescosta
  medium:            miguelptcosta1995
  google+:           
  goodreads:         migueltorrescosta
  linkedin:          miguel-torres-costa
  steam:             WalkinBot
  twitter:           worc4002
  stackoverflow:     7358944
  reddit:            WalkinBot

# Custom vars
version:             1.0.0

# Gems
plugins: [jekyll-gist,jekyll-sitemap,jekyll-seo-tag]